Tp-fcd: create router
frontend-park-mail-ru/2022_2_BugOverload pull request #11
Opened 2022-10-10 20:28 UTC by Mike5535

2022-10-11 11:09 UTC, Sarafa2n requested changes

2022-10-11 11:09 UTC, Sarafa2n commented on src/components/Collection/collection.js
> +        const response = await Ajax.get(`http://localhost:80/v1/${href}`);
эм

2022-10-11 11:09 UTC, Sarafa2n commented on src/components/Userbar/userbar.js
> +            const resGet = Ajax.get('http://localhost:80/v1/auth/logout');
80 порт не нужно указывать

2022-10-11 11:09 UTC, Sarafa2n commented on src/router/Router.js
> +    go(stateObject) {
А как переход будет работать, то есть куда мне нужно кликнуть чтобы перейти ?

2022-10-11 17:10 UTC, Mike5535 commented on src/components/Userbar/userbar.js
> +            const resGet = Ajax.get('http://localhost:80/v1/auth/logout');
для локального тестирования, пока вебпака нет

2022-10-11 17:10 UTC, Mike5535 commented on src/components/Collection/collection.js
> +        const response = await Ajax.get(`http://localhost:80/v1/${href}`);
для локального тестирования, пока вебпака нет

2022-10-11 19:21 UTC, Mike5535 commented on src/router/Router.js
> +    go(stateObject) {
теперь в методе start, навешивается событие на обработку переходов с историей

2022-10-14 07:46 UTC, Sarafa2n requested changes

2022-10-14 07:46 UTC, Sarafa2n commented on src/router/Router.js
> +        window.onpopstate = ({ state }) => setTimeout(() => {
давайте переделаем на addEventLisnter

2022-10-17 08:14 UTC, Sarafa2n requested changes

2022-10-17 08:14 UTC, Sarafa2n commented on src/config/config.js
> +    // { path: '/films/', renderView: renderFilm },
Это что за комменты?

2022-10-17 08:14 UTC, Sarafa2n commented on src/index.js
> +const rout = new Router(document.getElementById('root'));
Можно сделать из роутера синглтон и имптортить не класс, а инстанс

2022-10-17 08:14 UTC, Sarafa2n commented on src/router/Router.js
> +        const reg = new RegExp(`^${href.replace(hrefRegExp.idFilms, '(\\w+)')}?$`);
Раз уж выносишь регулярки выноси все

2022-10-17 08:14 UTC, Sarafa2n commented on src/router/Router.js
> +            // тут будет рендер 404 страницы
Тогда не просто коммент, а TODO

2022-10-21 13:07 UTC, merged