Tp e16 filmpage. Вёрстка страницы фильма
frontend-park-mail-ru/2022_2_BugOverload pull request #19
Opened 2022-10-26 19:03 UTC by Ivan-Bir

2022-10-29 10:08 UTC, Sarafa2n requested changes
Дофига закоменченого кода, его либо использовать либо убирать, так я не волью, остальное в целом норм

2022-10-29 10:08 UTC, Sarafa2n commented on src/components/AboutFilm/aboutFilm.css
> +    /* z-index: -1; */
убрать

2022-10-29 10:08 UTC, Sarafa2n commented on src/components/AboutFilm/aboutFilm.css
> +    /* height: 100vh; */
убрать

2022-10-29 10:08 UTC, Sarafa2n commented on src/components/AboutFilm/aboutFilm.js
> +                // isUsed: 'false',
Все комментарии нужно убирать когда кидаешь на проверку

2022-11-04 09:16 UTC, Sarafa2n requested changes

2022-11-04 09:16 UTC, Sarafa2n commented on src/components/AboutFilm/aboutFilm.scss
> +}
раз у нас уже scss давай писать как можно на scss &__blackout-left {}

2022-11-04 09:16 UTC, Sarafa2n commented on src/components/AboutFilm/aboutFilm.scss
> +  background-color: aquamarine;
а че не в переменке ?

2022-11-04 09:16 UTC, Sarafa2n commented on src/components/DetailsFilm/detailsFilm.scss
> +} */
ээээ

2022-11-04 09:16 UTC, Sarafa2n commented on src/components/InputReview/inputReview.scss
> +} */
эээээ

2022-11-04 09:16 UTC, Sarafa2n commented on src/components/Review/review.scss
> +  background-color: rgb(18 183 124 / 20%);
хм

2022-11-06 16:55 UTC, Sarafa2n requested changes

2022-11-06 16:55 UTC, Sarafa2n commented on src/components/AboutFilm/aboutFilm.js
> +        }
а может reduce ?

2022-11-06 16:55 UTC, Sarafa2n commented on src/components/AboutFilm/aboutFilm.js
> +        });
вынеси плз в отдельную

2022-11-06 16:55 UTC, Sarafa2n commented on src/components/AboutFilm/aboutFilm.scss
> +  color: #959595;
перенеси цвета в переменную

2022-11-06 16:55 UTC, Sarafa2n commented on src/components/DetailsFilm/detailsFilm.handlebars
> +        </div>
давай сделаем правильные отступы а то на одном уровне с if

2022-11-06 16:55 UTC, Sarafa2n commented on src/components/InputReview/inputReview.handlebars
> +</div>
пустая строка нужна

2022-11-06 16:55 UTC, Sarafa2n commented on src/utils/decorationData.js
> +    newList.push(list[i]);
reduce

2022-11-06 17:01 UTC, Ivan-Bir commented on src/utils/decorationData.js
> +    newList.push(list[i]);
newList.push(list[i] + ',');

2022-11-08 16:19 UTC, Sarafa2n approved these changes

2022-11-11 16:36 UTC, merged