Tp-8a5: create user profile
frontend-park-mail-ru/2022_2_BugOverload pull request #21
Opened 2022-10-30 19:20 UTC by Mike5535

2022-11-02 11:48 UTC, Sarafa2n requested changes

2022-11-02 11:48 UTC, Sarafa2n commented on src/components/Film/film.handlebars
> +            <div class="film__poster" style="background-image: url('http://movie-gate.online:8088/v1/image?object=film_poster_ver&key={{poster_ver}}{{!-- {{poster_ver}} --}}');"></div>
а может формировать url будем в js ?

2022-11-02 11:48 UTC, Sarafa2n commented on src/components/Header/header.handlebars
> +       {{!-- {{avatar}} --}}
комменты

2022-11-02 11:48 UTC, Sarafa2n commented on src/components/Modal/modal.scss
> +    /* align-content: center; */
0_0

2022-11-02 11:48 UTC, Sarafa2n commented on src/components/ProfileChange/profileChange.js
> +        changeButton.addEventListener('click', () => {
давай вынесем () => в отдельную переменную, так как ты не сможешь тогда отписаться от этого события

2022-11-02 11:48 UTC, Sarafa2n commented on src/components/ProfileChange/profileChange.js
> +        for (const key of Object.keys(forms)) {
давай переделаем на Foreach

2022-11-02 11:48 UTC, Sarafa2n commented on src/components/ProfileChange/profileChange.js
> +        for (const key of Object.keys(user)) {
тут тоже

2022-11-02 11:48 UTC, Sarafa2n commented on src/store/actionCreater/filmActions.js
> +//     value: {
это че?

2022-11-02 12:30 UTC, Mike5535 commented on src/store/actionCreater/filmActions.js
> +//     value: {
Это не моё, удалю

2022-11-03 13:43 UTC, Sarafa2n requested changes

2022-11-03 13:43 UTC, Sarafa2n commented on src/components/ErrorMessage/errorMessage.scss
> +    background-color: rgb(150 0 0);
а почему не токеном?

2022-11-03 13:43 UTC, Sarafa2n commented on src/components/ProfileMenu/_profileMenu.scss
> +    background: linear-gradient(to top, rgba(23 23 23 /100%), rgba(23 23 23 /0%));
тут тоже цвета не в переменых

2022-11-03 14:20 UTC, Sarafa2n approved these changes

2022-11-03 14:20 UTC, merged